workflows:
  ios-simulator-build:
    name: iOS Simulator Build for Appetize
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build iOS app for simulator (no signing)
        script: |
          xcodebuild build \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=18.0' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - ios/build/Runner.app
    publishing:
      email:
        recipients:
          - lovenicenoona22@gmail.com
