workflows:
  ios-simulator-build:
    name: iOS Simulator Build for Appetize
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean Xcode build folder
        script: |
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/Flutter/Flutter.framework
          rm -rf ios/Flutter/Flutter.podspec

      - name: Install Flutter dependencies
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build iOS app for simulator
        script: flutter build ios --simulator --debug

    artifacts:
      - build/ios/iphonesimulator/Runner.app

    publishing:
      email:
        recipients:
          - lovenicenoona22@gmail.com

  android-build:
    name: Android APK Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Build APK
        script: flutter build apk --debug

    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

    publishing:
      email:
        recipients:
          - lovenicenoona22@gmail.com
