name: my_live_streaming_app
description: A Flutter live streaming app using Agora SDK.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ เพิ่มแพ็กเกจที่จำเป็น
  agora_rtc_engine: ^6.2.2
  permission_handler: ^11.3.0

  # UI & Core
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
