name: joy_liveth
description: A Flutter live streaming app using Agora SDK and custom UI similar to Mico Live.

publish_to: 'none' # Remove if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ Core packages
  cupertino_icons: ^1.0.2
  permission_handler: ^11.3.0
  agora_rtc_engine: ^6.2.2
  http: ^1.4.0

  # ✅ UI/UX
  flutter_svg: ^2.0.7
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Regular.ttf
        - asset: assets/fonts/Prompt-Bold.ttf
          weight: 700
