# ios/Podfile

platform :ios, '12.0'
use_frameworks! :linkage => :static

# ✅ เพิ่มแหล่ง CocoaPods ที่ใช้ได้แน่นอน
source 'https://cdn.cocoapods.org/'

ENV['FLUTTER_ROOT'] ||= File.expand_path('../../flutter')
load File.join(ENV['FLUTTER_ROOT'], 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
